"""Composed Flappy Bird environment for local development.

GENERATED by scripts/compose.py. Do not edit by hand. The harness-side registry entry
(metadata + hooks) is intentionally omitted; locally you build the env directly:

    from sandbox.env import make_env
"""

from .env import default_action, make_env
from .overlay import extract_overlay

extract_overlay_static = None

__all__ = ["make_env", "extract_overlay", "extract_overlay_static", "default_action"]
