# GAME-SANDBOX-GENERATED-ENV: scripts/compose.py
"""Composed copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/compose.py from environments/spades/. Do not edit by hand. The
students' agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete
public registry metadata used by the browser relay and the injected harness entry.

This template targets Spades. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import (
    BuiltinAgent,
    EnvParameter,
    EnvParameterChoice,
    EnvPreset,
    EnvironmentMeta,
    PlayerBounds,
    SeatPlan,
    SeatDeclaration,
    SeatPlans,
)

from .spades import default_action, extract_overlay, extract_overlay_static, make_env

ENV_ID = "spades"
PLAYER_ID = "player_0"
META = EnvironmentMeta(
    **{
        "env_id": "spades",
        "display_name": "Spades",
        "description": (
            "Four-player partnership Spades: bid the tricks you will take, then follow suit and play "
            "them out with spades trump."
        ),
        "stepping": "sequential",
        "builtin_agents": (BuiltinAgent(name='naive', label='Naive agent'), BuiltinAgent(name='cautious', label='Cautious bidder')),
        "layout": SeatPlans(plans=(SeatPlan(key='partnership', title='Partnership', seats=(SeatDeclaration(players=(0, 2), restricted_builtin=None), SeatDeclaration(players=(1, 3), restricted_builtin=None))), SeatPlan(key='solo', title='Solo', seats=(SeatDeclaration(players=(0,), restricted_builtin=None), SeatDeclaration(players=(1,), restricted_builtin=None), SeatDeclaration(players=(2,), restricted_builtin=None), SeatDeclaration(players=(3,), restricted_builtin=None))))),
        "human_players": ("player_0", "player_1", "player_2", "player_3"),
        "human_timeout_ms": 60000,
        "recommended_episode_ticks": 56,
        "pace_interval_ms": None,
        "step_limit_ms": 1000,
        "episode_limit_ms": 120000,
        "messaging": True,
        "message_cap": 120,
        "llm": True,
        "renderer": "spades",
        "seat_order_matters": True,
        "view_interval_ms": 3000,
        "live_interval_ms": 900,
        "human_pause": "session",
        "parameters": (),
        "presets": (),
    }
)

__all__ = [
    "make_env",
    "extract_overlay",
    "extract_overlay_static",
    "default_action",
    "ENV_ID",
    "PLAYER_ID",
    "META",
]
