# GAME-SANDBOX-GENERATED-ENV: scripts/compose.py
"""Composed copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/compose.py from environments/skirmish_crane/. Do not edit by hand. The
students' agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete
public registry metadata used by the browser relay and the injected harness entry.

This template targets Skirmish at Crane Reach. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import (
    BuiltinAgent,
    EnvParameter,
    EnvParameterChoice,
    EnvPreset,
    EnvironmentMeta,
    PlayerBounds,
    SeatPlan,
    SeatDeclaration,
    SeatPlans,
)

from .skirmish_crane import default_action, extract_overlay, extract_overlay_static, make_env

ENV_ID = "skirmish_crane"
PLAYER_ID = "player_0"
META = EnvironmentMeta(
    **{
        "env_id": "skirmish_crane",
        "display_name": "Skirmish at Crane Reach",
        "description": (
            "A seeded, turn-based team tactics game in which separately running units coordinate "
            "through perception and delayed messages."
        ),
        "stepping": "sequential",
        "builtin_agents": (BuiltinAgent(name='naive', label='Naive'),),
        "layout": SeatPlans(plans=(SeatPlan(key='skirmish', title='Skirmish', seats=(SeatDeclaration(players=(0, 1, 2), restricted_builtin=None), SeatDeclaration(players=(3, 4, 5), restricted_builtin=None))), SeatPlan(key='army', title='Army', seats=(SeatDeclaration(players=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19), restricted_builtin=None), SeatDeclaration(players=(20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39), restricted_builtin=None))))),
        "human_players": ("player_0", "player_1", "player_2", "player_3", "player_4", "player_5", "player_6", "player_7", "player_8", "player_9", "player_10", "player_11", "player_12", "player_13", "player_14", "player_15", "player_16", "player_17", "player_18", "player_19", "player_20", "player_21", "player_22", "player_23", "player_24", "player_25", "player_26", "player_27", "player_28", "player_29", "player_30", "player_31", "player_32", "player_33", "player_34", "player_35", "player_36", "player_37", "player_38", "player_39"),
        "human_timeout_ms": 60000,
        "recommended_episode_ticks": 6000,
        "pace_interval_ms": None,
        "step_limit_ms": 1000,
        "episode_limit_ms": 600000,
        "messaging": True,
        "message_cap": 200,
        "llm": False,
        "renderer": "crane-reach-field",
        "seat_order_matters": True,
        "view_interval_ms": 1000,
        "live_interval_ms": 1000,
        "human_pause": "playback",
        "parameters": (EnvParameter(name='field_extent', title='Field extent', description='Hex distance from the center to the field edge.', type='int', default=7, min=5, max=22, choices=()), EnvParameter(name='terrain', title='Terrain', description='Enables water, hills, forests, and marshes.', type='bool', default=False, min=None, max=None, choices=()), EnvParameter(name='wasteland', title='Wasteland', description='Scatters magical waste that wounds any unit entering it. Needs terrain.', type='bool', default=False, min=None, max=None, choices=()), EnvParameter(name='unit_abilities', title='Unit abilities', description='Enables cavalry charge and footman shield wall.', type='bool', default=False, min=None, max=None, choices=()), EnvParameter(name='capture_zones', title='Capture zones', description='Number of scoring zones. Zero disables capture play.', type='int', default=0, min=0, max=5, choices=()), EnvParameter(name='capture_target', title='Capture target', description='Score needed to end a capture match.', type='int', default=200, min=10, max=10000, choices=()), EnvParameter(name='round_cap', title='Round cap', description='Maximum number of completed rounds.', type='int', default=1000, min=100, max=10000, choices=())),
        "presets": (EnvPreset(name='season_1', title='Season 1: The Skirmish', values={}, llm=False), EnvPreset(name='season_2', title='Season 2: The March', values={'terrain': True}, llm=False), EnvPreset(name='season_3', title='Season 3: The Army', values={'seat_plan': 'army', 'field_extent': 10, 'terrain': True, 'unit_abilities': True}, llm=False), EnvPreset(name='season_4', title='Season 4: The Commander', values={'seat_plan': 'army', 'field_extent': 10, 'terrain': True, 'unit_abilities': True, 'capture_zones': 1}, llm=False), EnvPreset(name='season_5', title='Season 5: The General', values={'seat_plan': 'army', 'field_extent': 10, 'terrain': True, 'unit_abilities': True, 'capture_zones': 3}, llm=False), EnvPreset(name='season_6', title='Season 6: The Rivals', values={'seat_plan': 'army', 'field_extent': 10, 'terrain': True, 'wasteland': True, 'unit_abilities': True, 'capture_zones': 3}, llm=False)),
    }
)

__all__ = [
    "make_env",
    "extract_overlay",
    "extract_overlay_static",
    "default_action",
    "ENV_ID",
    "PLAYER_ID",
    "META",
]
