# GAME-SANDBOX-GENERATED-ENV: scripts/compose.py
"""Composed copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/compose.py from environments/three_branches/. Do not edit by hand. The
students' agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete
public registry metadata used by the browser relay and the injected harness entry.

This template targets Days at Three Branches. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import (
    BuiltinAgent,
    EnvParameter,
    EnvParameterChoice,
    EnvPreset,
    EnvironmentMeta,
    PlayerBounds,
    SeatPlan,
    SeatDeclaration,
    SeatPlans,
)

from .three_branches import default_action, extract_overlay, extract_overlay_static, make_env

ENV_ID = "three_branches"
PLAYER_ID = "player_0"
META = EnvironmentMeta(
    **{
        "env_id": "three_branches",
        "display_name": "Days at Three Branches",
        "description": (
            "A seeded village day in which separately running NPCs make one village feel alive around "
            "a human-played visitor."
        ),
        "stepping": "simultaneous",
        "builtin_agents": (BuiltinAgent(name='naive', label='Naive'), BuiltinAgent(name='scripted_visitor', label='Scripted visitor')),
        "layout": SeatPlans(plans=(SeatPlan(key='cast_5', title='Five villagers', seats=(SeatDeclaration(players=(1, 2, 3, 4, 5), restricted_builtin=None), SeatDeclaration(players=(0,), restricted_builtin='scripted_visitor'))), SeatPlan(key='cast_10', title='Ten villagers', seats=(SeatDeclaration(players=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), restricted_builtin=None), SeatDeclaration(players=(0,), restricted_builtin='scripted_visitor'))))),
        "human_players": ("player_0",),
        "human_timeout_ms": None,
        "recommended_episode_ticks": 1200,
        "pace_interval_ms": 250,
        "step_limit_ms": 250,
        "episode_limit_ms": 120000,
        "messaging": True,
        "message_cap": 200,
        "llm": True,
        "renderer": "three-branches-village",
        "seat_order_matters": False,
        "view_interval_ms": 250,
        "live_interval_ms": None,
        "human_pause": "session",
        "parameters": (EnvParameter(name='daynight', title='Day and night', description='Enables the named day phases.', type='bool', default=False, min=None, max=None, choices=()),),
        "presets": (EnvPreset(name='season_1', title='Season 1: Village routines', values={}, llm=False), EnvPreset(name='season_2', title='Season 2: A larger village', values={'seat_plan': 'cast_10'}, llm=False), EnvPreset(name='season_3', title='Season 3: Village relationships', values={'seat_plan': 'cast_10'}, llm=False), EnvPreset(name='season_4', title='Season 4: Day and night', values={'seat_plan': 'cast_10', 'daynight': True}, llm=False), EnvPreset(name='season_5', title='Season 5: Village dialogue', values={'seat_plan': 'cast_10', 'daynight': True}, llm=True), EnvPreset(name='season_6', title='Season 6: Living village', values={'seat_plan': 'cast_10', 'daynight': True}, llm=True)),
    }
)

__all__ = [
    "make_env",
    "extract_overlay",
    "extract_overlay_static",
    "default_action",
    "ENV_ID",
    "PLAYER_ID",
    "META",
]
